version: '3.8'

services:
  app:
    build: .
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - UID=${UID}
      - GID=${GID}
    user: "${UID}:${GID}"
    networks:
      - symfony_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"  # сайт
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony_network

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"  # порт для phpPgAdmin
    networks:
      - symfony_network
  adminer:
    image: adminer
    ports:
      - "8082:8080"
    networks:
      - symfony_network
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
    networks:
      - symfony_network


networks:
  symfony_network:

volumes:
  pgdata:
  pgadmin_data: