security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        organizations:
            entity:
                class: App\Entity\Organization
                property: apiToken

    firewalls:
        api:
            pattern: ^/api
            stateless: true
            provider: organizations
            custom_authenticator: App\Security\OrganizationTokenAuthenticator
            entry_point: App\Security\OrganizationTokenAuthenticator
        main:
            pattern: ^/
            provider: app_user_provider
            lazy: true
            form_login:
                login_path: app_login
                check_path: app_login_check
                default_target_path: /dashboard
                enable_csrf: true
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 7 дней
                path: /

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/login_check$, roles: PUBLIC_ACCESS }
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard, roles: [ROLE_USER, ROLE_OWNER] }
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
